name: 'Hello World'
description: 'Greet someone'
inputs:
  ecr-repository:
    description: Name of your ECR repository
    required: true
  ecr-registry:
    description: Comma-separated string of ECR image tags
    required: true
  image-tag:
    description: Docker Image ECR image tag
    default: latest
  dockerfile-path:
    description: Name of Dockerfile to use
    default: Dockerfile
  extra-build-args:
    description: Extra flags to pass to docker build (see docs.docker.com/engine/reference/commandline/build)
    default: ""
outputs:
  image:
    description: "ECR Image Id"
    value: ${{ steps.output-tag.outputs.image }}
runs:
  using: "composite"
  steps:
    - run: echo "Build and push"
    
    - run: echo "image = ${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }}:${{ inputs.image-tag }}"

    - id: build
      run: docker build --cache-from ${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }}:${{ inputs.image-tag }} --cache-from ${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }}:latest -t ${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }}:${{ inputs.image-tag }} -t ${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }}:latest . -f ${{ inputs.dockerfile-path }}
    
    - id: push
      run: docker push ${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }} --all-tags
    
    - id: output-tag
      run: echo "image=${{ inputs.ecr-registry }}/${{ inputs.ecr-registry }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
    