name: Build and push Docker image

description: |
  Builds a Docker image from a Dockerfile and pushes it to an Amazon ECR repository.

inputs:
  ecr-registry:
    description: 'The Amazon ECR registry URI, e.g. 123456789012.dkr.ecr.us-west-2.amazonaws.com'
    required: true
    type: string
  ecr-repository:
    description: 'The name of the Amazon ECR repository to push the image to'
    required: true
    type: string
  image-tag:
    description: 'The tag to apply to the Docker image'
    required: true
    type: string
  dockerfile-path:
    description: 'The path to the Dockerfile to build, relative to the root of the repository'
    required: true
    type: string
  target:
    description: 'The target stage to build in the Dockerfile'
    required: false
    type: string
    default: ''
  extra-build-arg:
    description: 'Additional build arguments to pass to `docker build`'
    required: false
    type: string
    default: ''

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  image:
    description: "ECR Image Id"
    value: ${{ steps.output-tag.outputs.image }}

runs:
  using: "composite"
  steps:
    - name: Build and push Docker image
      run: build-and-push.sh \
          "${{inputs.ecr-registry}}" \
          "${{inputs.ecr-repository}}" \
          "${{inputs.image-tag}}" \
          "${{inputs.dockerfile-path}}" \
          "${{inputs.target}}" \
          "${{inputs.extra-build-arg}}"
      shell: bash
    - id: output-tag
      run: echo "image=${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
      shell: bash
