name: 'Hello World'

description: 'Greet someone'

inputs:
  ecr-registry:
    description: 'The Amazon ECR registry URI, e.g. 123456789012.dkr.ecr.us-west-2.amazonaws.com'
    required: true
    type: string
  ecr-repository:
    description: 'The name of the Amazon ECR repository to push the image to'
    required: true
    type: string
  image-tag:
    description: 'The tag to apply to the Docker image'
    required: true
    type: string
  dockerfile-path:
    description: 'The path to the Dockerfile to build, relative to the root of the repository'
    required: true
    type: string
  target:
    description: 'The target stage to build in the Dockerfile'
    required: false
    type: string
    default: ''
  extra-build-arg:
    description: 'Additional build arguments to pass to `docker build`'
    required: false
    type: string
    default: ''

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  image:
    description: "ECR Image Id"
    value: ${{ steps.output-tag.outputs.image }}

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
    - name: Build and push Docker image
      run: |
        ECR_REGISTRY="${{ inputs.ecr-registry }}"
        ECR_REPOSITORY="${{ inputs.ecr-repository }}"
        IMAGE_TAG="${{ inputs.image-tag }}"

        ECR_REGISTRY=$(echo "$ECR_REGISTRY" | xargs)
        ECR_REPOSITORY=$(echo "$ECR_REPOSITORY" | xargs)
        IMAGE_TAG=$(echo "$IMAGE_TAG" | xargs)

        build-and-push.sh \
          "$ECR_REGISTRY" \
          "$ECR_REPOSITORY" \
          "$IMAGE_TAG" \
          "${{ inputs.dockerfile-path }}" \
          "${{ inputs.target }}" \
          "${{ inputs.extra-build-arg }}"
      shell: bash
    - id: output-tag
      run: echo "image=${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
      shell: bash
